remote_theme: daattali/beautiful-jekyll

title: Jeff Wang
author: Jeff Wang

navbar-links:
  About Me: "aboutme"
  Research: "research"
  Fun: 

  
avatar: "https://github.com/jeffwang1001/jeffwang1001.github.io/blob/main/jeffwang.png"

round-avatar: true

social-network-links:
  email: "jeffwang1001@gmail.com"
  github: jeffwang1001
  linkedin: jeff-wang-ucla
  google-scholar: citations?user=PW5OX-YAAAAJ&hl=en
  

