remote_theme: daattali/beautiful-jekyll

title: Jeff Wang
author: Jeff Wang

navbar-links:
  About Me: "aboutme"
  Research: "README"
  

  
avatar: "https://github.com/jeffwang1001/jeffwang1001.github.io/blob/main/jeffwang.png"



