remote_theme: daattali/beautiful-jekyll

title: Jeff Wang
author: Jeff Wang

navbar-links:
  About Me: "aboutme"
  Research: "research"
  Fun: 

  
avatar: "/Desktop/jeffwang.png"

round-avatar: true

social-network-links:
  email: "jeffwang1001@gmail.com"
  github: jeffwang1001
  linkedin: jeff-wang-ucla
  google-scholar: citations?user=PW5OX-YAAAAJ&hl=en
  

