remote_theme: daattali/beautiful-jekyll

title: Jeff Wang
author: Jeff Wang

navbar-links:
  About Me: "aboutme"
  Research: "research"
  Fun: "fun"
  Contact: "contact"
  Blog: "blog"
   
  
avatar: "/jeffwang.png"

round-avatar: true

social-network-links:
  email: "jeffwang1001@gmail.com"
  github: jeffwang1001
  linkedin: jeff-wang-ucla
  google-scholar: citations?user=PW5OX-YAAAAJ&hl=en
  ORCID: 0000-0002-4164-1264
 
  
  
  
navbar-col: "#bd5f00"  
footer-col: "#bd5f00"


  

