theme: jekyll-theme-minimal
title: Jeff Wang
author: Jeff Wang

navbar-links:
  About Me: "aboutme"
  
avatar: "

[params.social]
  icon = "google-scholar"
  icon_pack = "ai"
  link = "https://scholar.google.com/citations?user=PW5OX-YAAAAJ&hl=en"
